"""empty message

Revision ID: 1304f5e826f0
Revises: eeac7b2f4174
Create Date: 2019-07-09 10:41:41.813417

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1304f5e826f0'
down_revision = 'eeac7b2f4174'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('network',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('cidr', postgresql.CIDR(), nullable=False),
    sa.Column('defaults', sa.Text(), server_default='{}', nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('network')
    # ### end Alembic commands ###
