"""empty message

Revision ID: 333899f80da1
Revises: bd02666d9b33
Create Date: 2019-08-23 18:08:11.525295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '333899f80da1'
down_revision = 'bd02666d9b33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('build', 'iteration')
    op.add_column('release', sa.Column('iteration', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('release', 'iteration')
    op.add_column('build', sa.Column('iteration', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
