"""empty message

Revision ID: 333ff092c738
Revises: 79c77a6d4751
Create Date: 2019-07-09 10:51:43.388440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '333ff092c738'
down_revision = '79c77a6d4751'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('domain', sa.Column('name', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('domain', 'name')
    # ### end Alembic commands ###
