"""empty message

Revision ID: 3dcdc8ab9806
Revises: 1304f5e826f0
Create Date: 2019-07-09 10:48:05.157425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dcdc8ab9806'
down_revision = '1304f5e826f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domain',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('defaults', sa.Text(), server_default='{}', nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('network', sa.Column('domain_id', sa.String(), nullable=True))
    op.add_column('network', sa.Column('name', sa.String(), nullable=False))
    op.create_foreign_key(None, 'network', 'domain', ['domain_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'network', type_='foreignkey')
    op.drop_column('network', 'name')
    op.drop_column('network', 'domain_id')
    op.drop_table('domain')
    # ### end Alembic commands ###
