"""empty message

Revision ID: 46ac59e31fad
Revises: 82d2c81b9b72
Create Date: 2019-08-23 11:46:30.857484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46ac59e31fad'
down_revision = '82d2c81b9b72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('build',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('service_id', sa.String(), nullable=False),
    sa.Column('git_tag', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('build')
    # ### end Alembic commands ###
