"""empty message

Revision ID: 51fe9c5b48ed
Revises: d9df4379133c
Create Date: 2019-07-03 17:10:59.161799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51fe9c5b48ed'
down_revision = 'd9df4379133c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('docker_image', sa.String(), nullable=True))
    op.drop_column('service', 'docker_image_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('docker_image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('service', 'docker_image')
    # ### end Alembic commands ###
