"""empty message

Revision ID: 65c77e24f90c
Revises: 333ff092c738
Create Date: 2019-07-10 17:45:36.708246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65c77e24f90c'
down_revision = '333ff092c738'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('process',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('service_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deployment_process',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('deployment_id', sa.String(), nullable=True),
    sa.Column('process_id', sa.String(), nullable=True),
    sa.Column('defaults', sa.Text(), server_default='{}', nullable=True),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployment.id'], ),
    sa.ForeignKeyConstraint(['process_id'], ['process.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resource_allocation',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('deployment_process_id', sa.String(), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.Column('defaults', sa.Text(), server_default='{}', nullable=True),
    sa.ForeignKeyConstraint(['deployment_process_id'], ['deployment_process.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resource_allocation')
    op.drop_table('deployment_process')
    op.drop_table('process')
    # ### end Alembic commands ###
