"""empty message

Revision ID: 68e4cf010220
Revises: 5e1a86d9fa1d
Create Date: 2019-07-13 09:44:49.107678

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '68e4cf010220'
down_revision = '5e1a86d9fa1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subnet',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('cidr', postgresql.CIDR(), nullable=False),
    sa.Column('network_id', sa.String(), nullable=False),
    sa.Column('defaults', sa.Text(), server_default='{}', nullable=True),
    sa.ForeignKeyConstraint(['network_id'], ['network.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subnets_nodegroups',
    sa.Column('subnet_id', sa.String(), nullable=True),
    sa.Column('nodegroup_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['nodegroup_id'], ['nodegroup.id'], ),
    sa.ForeignKeyConstraint(['subnet_id'], ['subnet.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subnets_nodegroups')
    op.drop_table('subnet')
    # ### end Alembic commands ###
