"""empty message

Revision ID: 79c77a6d4751
Revises: 3dcdc8ab9806
Create Date: 2019-07-09 10:49:29.056522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79c77a6d4751'
down_revision = '3dcdc8ab9806'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('domain', sa.Column('environment_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'domain', 'environment', ['environment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'domain', type_='foreignkey')
    op.drop_column('domain', 'environment_id')
    # ### end Alembic commands ###
