"""empty message

Revision ID: 82d2c81b9b72
Revises: f6db461aa99e
Create Date: 2019-07-17 14:11:41.521808

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '82d2c81b9b72'
down_revision = 'f6db461aa99e'
branch_labels = None
depends_on = None


def upgrade():
    watermark = postgresql.ENUM('HIGH', 'LOW', name='watermark')
    watermark.create(op.get_bind())
    op.add_column('resource_allocation', sa.Column('watermark', watermark, nullable=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource_allocation', 'watermark')
    # ### end Alembic commands ###
    watermark = postgresql.ENUM('HIGH', 'LOW', name='watermark')
    watermark.drop(op.get_bind())
