"""empty message

Revision ID: a33d6f0a9296
Revises: b0f02c209613
Create Date: 2019-07-03 11:35:30.636469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a33d6f0a9296'
down_revision = 'b0f02c209613'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('services_service_configs')
    op.add_column('service_config', sa.Column('name', sa.String(length=64), nullable=False))
    op.add_column('service_config', sa.Column('service_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'service_config', 'service', ['service_id'], ['id'])
    op.drop_column('service_config', 'defaults')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_config', sa.Column('defaults', sa.TEXT(), server_default=sa.text("'{}'::text"), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'service_config', type_='foreignkey')
    op.drop_column('service_config', 'service_id')
    op.drop_column('service_config', 'name')
    op.create_table('services_service_configs',
    sa.Column('service_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('service_config_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['service_config_id'], ['service_config.id'], name='services_service_configs_service_config_id_fkey'),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], name='services_service_configs_service_id_fkey')
    )
    # ### end Alembic commands ###
