"""empty message

Revision ID: b0f02c209613
Revises: 
Create Date: 2019-07-03 11:30:41.266315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0f02c209613'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('defaults', sa.Text(), server_default='{}', nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artifact_repository',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.Column('url', sa.String(length=253), nullable=True),
    sa.Column('defaults', sa.Text(), server_default='{}', nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('config_type',
    sa.Column('id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('environment',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('deployment_url', sa.String(), nullable=True),
    sa.Column('defaults', sa.Text(), server_default='{}', nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provider',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('defaults', sa.Text(), server_default='{}', nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_config',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('defaults', sa.Text(), server_default='{}', nullable=True),
    sa.Column('service_config', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deployment_target',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('environment_id', sa.String(), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.Column('defaults', sa.Text(), server_default='{}', nullable=True),
    sa.ForeignKeyConstraint(['environment_id'], ['environment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('region',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('provider_id', sa.String(), nullable=False),
    sa.Column('defaults', sa.Text(), server_default='{}', nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['provider.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stack',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('application_id', sa.String(), nullable=False),
    sa.Column('defaults', sa.Text(), server_default='{}', nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('stack_id', sa.String(), nullable=False),
    sa.Column('scm_url', sa.String(), nullable=True),
    sa.Column('docker_image_url', sa.String(), nullable=True),
    sa.Column('defaults', sa.Text(), server_default='{}', nullable=True),
    sa.ForeignKeyConstraint(['stack_id'], ['stack.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zone',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('region_id', sa.String(), nullable=False),
    sa.Column('defaults', sa.Text(), server_default='{}', nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deployment',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('service_id', sa.String(), nullable=True),
    sa.Column('deployment_target_id', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('tag', sa.String(), nullable=False),
    sa.Column('defaults', sa.Text(), server_default='{}', nullable=True),
    sa.ForeignKeyConstraint(['deployment_target_id'], ['deployment_target.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('services_service_configs',
    sa.Column('service_id', sa.String(), nullable=True),
    sa.Column('service_config_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['service_config_id'], ['service_config.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], )
    )
    op.create_table('config',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('config_type_id', sa.String(), nullable=True),
    sa.Column('deployment_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('tag', sa.String(), nullable=False),
    sa.Column('config', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['config_type_id'], ['config_type.id'], ),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deployments_zones',
    sa.Column('deployment_id', sa.String(), nullable=True),
    sa.Column('zone_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployment.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zone.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deployments_zones')
    op.drop_table('config')
    op.drop_table('services_service_configs')
    op.drop_table('deployment')
    op.drop_table('zone')
    op.drop_table('service')
    op.drop_table('stack')
    op.drop_table('region')
    op.drop_table('deployment_target')
    op.drop_table('service_config')
    op.drop_table('provider')
    op.drop_table('environment')
    op.drop_table('config_type')
    op.drop_table('artifact_repository')
    op.drop_table('application')
    # ### end Alembic commands ###
