"""empty message

Revision ID: bd02666d9b33
Revises: 4ab9f6bc8410
Create Date: 2019-08-23 16:39:55.950450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd02666d9b33'
down_revision = '4ab9f6bc8410'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('build', sa.Column('iteration', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('build', 'iteration')
    # ### end Alembic commands ###
