"""empty message

Revision ID: c15101d9f0cc
Revises: 68e4cf010220
Create Date: 2019-07-13 09:55:42.129253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c15101d9f0cc'
down_revision = '68e4cf010220'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('network', 'domain_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('network', 'domain_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
