"""empty message

Revision ID: d9df4379133c
Revises: a33d6f0a9296
Create Date: 2019-07-03 17:08:48.526524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9df4379133c'
down_revision = 'a33d6f0a9296'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('artifact_repository_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'service', 'artifact_repository', ['artifact_repository_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'service', type_='foreignkey')
    op.drop_column('service', 'artifact_repository_id')
    # ### end Alembic commands ###
