"""empty message

Revision ID: eeac7b2f4174
Revises: 51fe9c5b48ed
Create Date: 2019-07-03 17:11:26.310557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eeac7b2f4174'
down_revision = '51fe9c5b48ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('artifact_name', sa.String(), nullable=True))
    op.drop_column('service', 'docker_image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('docker_image', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('service', 'artifact_name')
    # ### end Alembic commands ###
