"""empty message

Revision ID: f6db461aa99e
Revises: c15101d9f0cc
Create Date: 2019-07-15 19:16:24.851674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6db461aa99e'
down_revision = 'c15101d9f0cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artifact_repository', sa.Column('name', sa.String(), server_default='artifact-repo', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artifact_repository', 'name')
    # ### end Alembic commands ###
